name: Build for Windows

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build-windows:
    name: Build for Windows 🪟
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master

      - name: Configure CMake
        run: |
          cmake -B build -S . -G "Ninja" -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Upload Plugin DLL
        uses: actions/upload-artifact@v4
        with:
          name: HaL-Visor-Windows
          path: build/**/*.dll